[package]
name = "market-maker"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.9.2"
tokio = { version = "1.28.1", features = ["full"] }
prost = "0.11"
async-trait = "0.1.68"
tokio-stream = "0.1.14"
futures = "0.3.28"
tokio-tungstenite = "0.19.0"
url = "2.3.1"
futures-util = "0.3.28"

[[bin]]
name = "market-maker"
path = "src/main.rs"
