io_thread_percentage: 0.6
exchanges:
  - client_name: "binance_global_1"
    exchange_name: 0
    snapshot_enabled: true
    http_client: true
    snapshot_uri: "https://api.binance.com/api/v3/depth?symbol=BTCUSDT&limit=5000"
    ws_uri: "wss://stream.binance.com:9443"
    depth: 5000
    buffer_size: 1000
    watched_pair: "USDT/BTC"
    orderbook_subscription_message: "Subscribe to BTC/USD"
    tick_size: 0.01
    ticker: "BTC/USD"
  - client_name: "binance_usa_1"
    exchange_name: 2
    snapshot_enabled: true
    http_client: true
    snapshot_uri: "https://api.binance.us/api/v3/depth?symbol=BTCUSDT&limit=5000"
    ws_uri: "wss://stream.binance.us:9443"
    depth: 5000
    buffer_size: 1000
    watched_pair: "USDT/BTC"
    orderbook_subscription_message: "Subscribe to ETH/USD"
    tick_size: 0.01
    ticker: "BTC/USD"
  - client_name: "bybit_1"
    exchange_name: 3
    snapshot_enabled: true
    http_client: true
    snapshot_uri: "https://api.bybit.com/spot/v3/public/quote/depth?symbol=BTCUSDT&limit=5000"
    ignore_snapshot_websocket: true
    ws_uri: "wss://stream-testnet.bybit.com/v5/public/spot"
    depth: 5000
    buffer_size: 1000
    watched_pair: "USDT/BTC"
    orderbook_subscription_message: "Subscribe to ETH/USD"
    tick_size: 0.01
    ticker: "BTC/USD"

orderbook:
  ring_buffer:
    ring_buffer_size: 17500
    channel_buffer_size: 1500
  price_point_array_size: 100
grpc_server:
  host_uri: "127.0.0.1:9090"
